### ISSUE TITLE
Map zoom out

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#1]
I believe that our tool will have major issues presenting the data for large areas. In order to avoid bad user experience, we may need to define maximal zoom out (e..g 2x the project area or 100km or???)

The actual maximal zoom out should be the one that's reasonably responsible on a relatively good PC with a relatively good internet connection, but we shouldn't expect too much here. E.g. my laptop on a WIFI in ATOS meeting room should work.

**Comment by p-a-s-c-a-l** [comment]
@therter Additionally, we have to restrict the size of the study area so that the user is not able to perform an assessment for e.g. a whole country. At the moment I propose a maximum of 100km².

Later, the actual maximum size of the study area has to be defined by @bernhardsk based on estimates / tests related to resource consumption, time to run the impact models in Emikat, time to publish the map layers in GeoServer, etc.

**Comment by therter** [comment]
The size of the study area is restricted to a maximum of 100km² and the maximum [zoom out level](https://leafletjs.com/examples/zoom-levels/) is restricted to 11, except for the study area selection.
