### ISSUE TITLE
Demo user cannot retrieve the study area

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#13]
The admin user retrieves the study area by the following url https://csis.myclimateservice.eu/jsonapi/group/study?filter[id][condition][path]=id&filter[id][condition][operator]=%3D&filter[id][condition][value]=1

But the demo user does not retrieve the study area. I think this is a problem with the permission. Perhaps you can help @patrickkaleta  @fgeyer16

**Comment by patrickkaleta** [comment]
@therter thanks for the hint. Indeed it seems like a permission issue. More specifically, it seems like a permission issue for the used filter, since https://csis.myclimateservice.eu/jsonapi/group/study can be accessed by the demo user.

When changing the [permissions](https://csis.myclimateservice.eu/admin/people/permissions) and allowing for authenticated users to "Administer group settings" the mentioned url can be accessed by the demo user and the study area gets displayed as expected. However, I don't thinks that's the right setting and authenticated users shouldn't be able to administer group settings, so I took back those changes after testing this.

@fgeyer16: any idea, where else we could change the permissions, so that authenticated users (like the demo user) can access the above mentioned url?

**Comment by therter** [comment]
As workaround I have added the "Administer group settings" permission to the authenticated users. This allows the demo user to use the maps

**Comment by p-a-s-c-a-l** [comment]
Is there a solution available, or are you still using the workaround?

**Comment by therter** [comment]
The workaround is still in use.

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

Any idea how to resolve this issue?

**Comment by patrickkaleta** [comment]
I believe I found the [root problem](https://www.drupal.org/project/jsonapi/issues/3037519). According to [this change](https://www.drupal.org/sa-contrib-2018-081) there used to be a problem with "access bypass" when using certain filters on custom entities. And apparently the Group type is considered a custom entity by the JSON API. That explains why the demo user was still able to view the group, when no filters were applied.

Implementing the two hooks as [mentioned](https://www.drupal.org/project/jsonapi/issues/3037519#comment-12999541) in the issue seems to do the trick and the workaround is no longer necessary. I believe it would be best if we add those two hooks into the csis_helpers module. 
@fgeyer16 what's your opinion?

**Comment by fgeyer16** [comment]
Keeping all fixes and improvements for the csis in one place is a good idea. But maybe we should separate some parts of the csis_helpers module in child modules (modules inside of modules). SO we can switch off single parts if the make problems after an update or are not needed any more because drupal core or a module can do the stuff in a never version. Then there is no need to modify code, just switch it of.
Concerning the study area, there is also a rest view which only provides the study area (I think I made it ages ago): https://csis.myclimateservice.eu/rest/study/1/area
Since it is a view we ca nset the permissions in the UI.

**Comment by patrickkaleta** [comment]
>Keeping all fixes and improvements for the csis in one place is a good idea. But maybe we should separate some parts of the csis_helpers module in child modules (modules inside of modules). SO we can switch off single parts if the make problems after an update or are not needed any more because drupal core or a module can do the stuff in a never version. Then there is no need to modify code, just switch it of.
Concerning the study area, there is also a rest view which only provides the study area (I think I made it ages ago): https://csis.myclimateservice.eu/rest/study/1/area
Since it is a view we ca nset the permissions in the UI.

@therter could you try to retrieve the study area using the Rest view created by Florian. If so, we wouldn't need to include the fix I previously mentioned. If not, I'll have a look at that proposed "module in a module" solution by @fgeyer16 
<br>
BTW....
> The admin user retrieves the study area by the following url [https://csis.myclimateservice.eu/jsonapi/group/study?filter[id][condition][path]=id&filter[id][condition][operator]=%3D&filter[id][condition][value]=1](https://csis.myclimateservice.eu/jsonapi/group/study?filter%5Bid%5D%5Bcondition%5D%5Bpath%5D=id&filter%5Bid%5D%5Bcondition%5D%5Boperator%5D=%3D&filter%5Bid%5D%5Bcondition%5D%5Bvalue%5D=1)

@therter is this link even being used anymore? Because even as an admin I'm getting an empty response. I'm not very familiar with filtering in the JSON:API, but in my opinion a better way of getting the study area based on the ID of the group would be:
https://csis.myclimateservice.eu/jsonapi/group/study?filter[drupal_internal__id]=1&fields[group--study]=field_area

**Comment by therter** [comment]
> @therter could you try to retrieve the study area using the Rest view created by Florian. If so, we wouldn't need to include the fix I previously mentioned. If not, I'll have a look at that proposed "module in a module" solution by @fgeyer16

I am testing it.

> @therter is this link even being used anymore? Because even as an admin I'm getting an empty response.

This link is still used, but as ID, the uuid is now required. 
Example: 
https://csis.myclimateservice.eu/jsonapi/group/study?filter[id][condition][path]=id&filter[id][condition][operator]=%3D&filter[id][condition][value]=c3609e3e-f80f-482b-9e9f-3a26226a6859

**Comment by patrickkaleta** [comment]
As was briefly discussed during our plenary meeting, using the REST-view created by @fgeyer16 is not a feasible solution since @therter needs to access various other data besides the study area. So I implemented the proposed hook in https://github.com/clarity-h2020/map-component/issues/13#issuecomment-506272720 in the csis_helpers module and deactivated the [workaround](https://github.com/clarity-h2020/map-component/issues/13#issuecomment-475575215).

@therter please check if it is all still working for the demo user or if additional work is needed.

**Comment by therter** [comment]
@patrickkaleta thanks, I have checked the react components and they are still working. So this issue can be closed.
