### ISSUE TITLE
Data Package Support

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#2]
The Map Component must access the meta-data of the Data Package (Example: [Background Layers](https://github.com/clarity-h2020/data-package/issues/7)) of the current Study stored in the CSIS via the [JSON API](https://github.com/clarity-h2020/docker-drupal/issues/43) and initialize the LayerControl Component with the respective layers. The LayerControl Component must support grouping of layers into different categories. Relevant properties to define the groups are
- [data_resource/title](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A5): title of the resource in layer control element
- [data_resource/path](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A16): the URI to build the WMS/WFS request. Needs possibly to be parsed and bbox request parameter to be provided
- [data_resource/analysis_context/workflow_step](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A48): for now we show only layers that are valid in the current context (so no subfolders for different steps)
- [data_resource/analysis_context/resource_type](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A16): Can be used for top level categories (folders) like [background layers](https://github.com/clarity-h2020/data-package/issues/4)
- [data_resource/analysis_context/scenario](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A47): could be used in HC, HC-LE and EE (IA [currently under discussion](https://github.com/clarity-h2020/data-package/issues/2#issuecomment-441222978)) for sub-level categories 

This information provided in properties of the Data Package / Data Resource should be enough to build and initial categories tree for the Map Component / Layer Control:

![grafik](https://user-images.githubusercontent.com/1788226/49016929-d159c380-f187-11e8-92c7-60f71265a7f7.png)

If additional categorisation is needed (example in figure below), the Data Package specification has [to be extended](https://github.com/clarity-h2020/data-package/issues/new). 

![grafik](https://user-images.githubusercontent.com/1788226/49016868-aa9b8d00-f187-11e8-9429-9290f8db64a7.png)

**Comment by maesbri** [comment]
I am not that sure that it would require extending the data package specification.
Following the above example for the population, to me, those are three population density data resources contained in the data package, with their own properties values.

**Comment by p-a-s-c-a-l** [comment]
Yes but how to decide if an exposure resource is put into the folder population or buildings if there is no additional categorisation property at the level of the data resource and the Data Package contains several Exposure resources (identified by data_resource/analysis_context/resource_type) that belong to several logical categories?

**Comment by maesbri** [comment]
Indeed, we need a 'category' property with possible values: population, buildings, etc.... 

The more I think about all these specific parameters, the more I am convinced that we should have a general resource with common attributes and the specialized resources (for BackgroundLayer, Exposure, Impact, etc.) with their specific properties, like the category for the Exposure and Impact analysis.

I need to think a bit about it since this would also introduce other problems, like repeating the same resource for each of the steps in the workflow where it is used.

**Comment by p-a-s-c-a-l** [comment]
We'll try to define a REST View to simplify the extraction of the relevant properties from the study and data package entities. See https://github.com/clarity-h2020/csis/issues/22#issuecomment-444460565

**Comment by patrickkaleta** [comment]
@therter 
so for now I created two REST Views:

- the **REST Group View** with the display: **Map Component** (/admin/structure/views/view/rest_group/edit)
-- it returns the links to the second REST view for each resource in the data package used by the study

- the **REST Node View** with the displays: **Map comp. dataset** and **Map comp. analysis. context** (/admin/structure/views/view/rest_node/edit)
-- **Map Compoment dataset** returns the title and path of the resource and the result of the **Map Component Analysis context** (workflow_step, resource_type and scenario)

I'm not sure if this nested View approach really works (meaning the JSON result is valid but it might be difficult to parse the result), so please check this and if necessary I will change this last part and return only the link to the **Map Component Analysis context** display instead of its result. The whole process would then take in total 3 calls instead of just 2, but since you [mentioned](https://github.com/clarity-h2020/csis/issues/22#issuecomment-445744785) that this wouldn't be a problem for the map compoment, we could do it that way.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta @fgeyer16 

What's the relation of Rest Views to the  [JSON:API vs. core's REST Module](https://github.com/clarity-h2020/docker-drupal/issues/43)? We should't mix APIs so we have to make a decision for either JSON:API or REST Module!

**Comment by fgeyer16** [comment]
@p-a-s-c-a-l  @patrickkaleta 
JSON API has a Filtering functionality as you can read [here](https://www.drupal.org/docs/8/modules/jsonapi/filtering). And I just read that you can [embed referenced entities](https://www.drupal.org/docs/8/modules/jsonapi/includes) with JSON API. Which would be a possibility to reduce REST calls here: [https://github.com/clarity-h2020/csis/issues/22](https://github.com/clarity-h2020/csis/issues/22)
This would speak for the JSON API. What I do like better on Rest views is that the Interface is nicer. What I mean is that you do not have to create a big HTML query string for filtering if a great part of the filter is always the same and only one or two parameters are exposed to the user of the interface. 
Since there is the idea of csis being open to service providers for integrating their own service a "easy" REST interface is maybe more appealing to the service providers.

Do we want to have a API which delivers a big amount of data (from which we maybe need only a small piece) with one call. Or do we want a more talking API where we have to ask for every piece with a separate call? The second case is maybe better if the external services have a lot of logic inside and need different data in different cases.

What do you think?

**Comment by p-a-s-c-a-l** [comment]
I'm in favour of the JSON API as I have the impression it will replace the REST API in the long term. While it's true that it's up to the client developer to build some complex query strings (once!), it gives us more flexibility and reduces maintenance effort and complexity at level of the Drupal side (no need to create REST Views for each and every special case).

What I don't like is the is the structure of the JSON documents, that's far from being clean and simple. Those aren't the javascript *objects* you really want to work with at client side. Referring to the example (which is btw rather confusing with its mixture of id, uid and uuid), I want to access `article.comment[0].user` and not iterating over `included` arrays by `data.relationships.field_comments.data[0].id` and `relationships.uid.data.id`.

So we have to put more effort in the client logic that maps these complex JSON objects into the simple state models of our applications (see point 3 and 4 in [this issue](https://github.com/clarity-h2020/csis/issues/46#issue-390262842)). But I don't expect that the JSON you'll get from the REST Views will look much better.

**Comment by p-a-s-c-a-l** [comment]
Basic Data Package Support is available. Now we have to deal with the changes to the DP Specification.
