### ISSUE TITLE
Restricted Study Area

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#24]
Decision: the end-user will not be able to define ~the~ **an arbitrary** the study area. He will select a city area the from a predefined list of cities (from urban atlas) for which we have all the necessary data to perform the screening study.

ATOS will check the list the cities (in urban atlas) for which we have all the layers to perform the local effects calculations, then generate a shapefile with country code+ city name+ bounding box of the city.

We import this Shapfile as Taxonomy, similar to the countries Taxonomy. When the user has selected a country, we filter the list of cities by country code. In addition to the study area field (geometry), we add a new field (e.g. 'city') to the Study Entity Type.

~~In the map component, we disable the controls for creating bounding boxes, etc..~~ The selection of the city should be done in Drupal, the map component will then fetch the city entity associated with the study entity and show the polygon (as country done with countries). **The definition of the study are will then only be possible within the bounds of the selected city.**

The actual selection of the city could be implemented in the 'context' tab. That means, the list of selectable cities in the city selection box depends on the selection the user has made in the countries box (filtered by country code!). @fgeyer16 @patrickkaleta Is that possible?

- [x] Create City / Region Taxonomy
- [x] Import Shafile / GeoJson / ... provided by ATOS
- [x] Update Context Tab and Study Area Entity add conditional (depending on country) selection box for citities / regions
- [x] Update Map Component, implement [KISS  approach](https://github.com/clarity-h2020/map-component/issues/24#issuecomment-496434276)

**Comment by humerh** [comment]
This was not exactly my understanding:
Yes, we sayed, that we will select a citiy area from a predefined list of cities (from urban atlas) for which we have all the necessary data to perform the screening study.
But I cannot remember, that we decided to omit the possibility to select a bounding box for the study area!
For us it would mean, that we get much larger study areas as we discussed till now.

Currently our Test-Area has  about 15kmx10km.
Pascals interpretation of study area would mean:  100kmx100km and more.

For us this decision (omitting of a meaningfull study area) would have a completely redesign of our algoithmus.

We should keep defining study areas inside the given project region.

**Comment by p-a-s-c-a-l** [comment]
@humerh is right, Issue description  updated accordingly.

The 1st KISS approach for the implementation is to disallow the panning and zooming beyond the selected city / region bounds.

**Comment by RobAndGo** [comment]
Sorry for my late reply, but I had to remove some errors from the method I was using and then confirm that it would work. 
Anyhow, here is just some preliminary results of what I thought I could deliver.

I am in the processing of updating the heat wave hazard events and determining the events:
- "Frequent" (Probability = 1.0; yearly event), 
- "Occasional" (Probability = 0.2; 1 in 5 year event), 
- "Rare" (Probability = 0.05; 1 in 20 year event)
A subset of the data looks like this:

`RCP_Period_Xcoord_Ycoord;Frequent(1.0);Occasional(0.2);Rare(0.05);`
`rcp45_20110101-20401231_X1_Y1;2d_30C;2d_38C;19d_36C;`
`rcp45_20110101-20401231_X1_Y2;2d_34C;3d_36C;9d_36C;` 
`rcp45_20110101-20401231_X1_Y3;2d_28C;12d_30C;6d_34C;` 
`rcp45_20110101-20401231_X1_Y4;3d_28C;11d_32C;12d_34C;` 
`rcp45_20110101-20401231_X1_Y5;2d_36C;7d_34C;2d_38C; `
`rcp45_20110101-20401231_X1_Y6;4d_34C;5d_36C;14d_36C;` 
`rcp45_20110101-20401231_X1_Y7;3d_38C;5d_40C;12d_40C; `
`rcp45_20110101-20401231_X1_Y8;2d_40C;12d_36C;19d_38C;` 
`rcp45_20110101-20401231_X1_Y9;3d_34C;3d_38C;10d_36C; `
`rcp45_20110101-20401231_X1_Y10;2d_28C;8d_28C;2d_32C; `
`rcp45_20110101-20401231_X1_Y11;3d_24C;5d_26C;13d_26C;` 
`rcp45_20110101-20401231_X1_Y12;4d_28C;6d_30C;2d_32C; `
`rcp45_20110101-20401231_X1_Y13;3d_32C;7d_32C;11d_32C;` 
`rcp45_20110101-20401231_X1_Y14;2d_40C;4d_40C;5d_40C;` `

The fields are defined in the header (first) line:
Field:
1. rcp26, rcp45, rcp85 or baseline _
             period: 19710101-20001231, 20110101-20401231, 20410101-20701231, 20710101-21001230 _ 
             X coordinate _ 
             Y coordinate 
2. Frequent event represented as duration in days and temperature in C, i.e. 2d_30C
3. Occasional event represented as duration in days and temperature in C, i.e. 2d_30C
4. Rare event represented as duration in days and temperature in C, i.e. 19d_36C

I have the coordinates for each grid box within the EURO-CORDEX data set. The files themselves reference grid coordinates in the form X,Y. The corresponding latitude,longitude I have in a file of the form:

`  x   y :  latitude   longitude`
`  1   1 :  29.952276  -8.075616`
`  1   2 :  30.055091  -8.120772`
`  1   3 :  30.157890  -8.166022`
`  1   4 :  30.260673  -8.211366`
`  1   5 :  30.363441  -8.256806`
`  1   6 :  30.466193  -8.302341`
`  1   7 :  30.568929  -8.347972`
`  1   8 :  30.671650  -8.393699`
`  1   9 :  30.774354  -8.439524`
`  1  10 :  30.877042  -8.485447`
`  1  11 :  30.979714  -8.531469`
`  1  12 :  31.082369  -8.577590`
`  1  13 :  31.185008  -8.623810`
`  1  14 :  31.287631  -8.670131`
`
What I wanted to do was to replace the X,Y grid coordinates in the first file with the latitude and longitude, but I realised that the original data was not quite right, which is why I was delayed with my answer.

The plan here is to have separate data files showing:
1. baseline 19710101-20001231
2. rcp26 20110101-20401231
3. rcp26 20410101-20701231
4. rcp26 20710101-21001231
5. rcp45 20110101-20401231    - presented above
6. rcp45 20410101-20701231
7. rcp45 20710101-21001231
8. rcp85 20110101-20401231
9. rcp85 20410101-20701231
10. rcp85 20710101-21001231

Each file will have the data for 345 x 351 = 121095 grid points. At the moment I will have the files in ASCII format and each would have a size of about 10Mb.

**Comment by negroscuro** [comment]
I have a table very similar fmro some months ago in order to know which cities are already loaded into the system. So the only difference is I have to add the country code. It looks like this:
CREATE TABLE public.city
(
    id integer NOT NULL DEFAULT nextval('city_id_seq'::regclass),
    name character varying(32) COLLATE pg_catalog."default",
    heat_wave boolean DEFAULT false,
    pluvial_flood boolean DEFAULT false,
    bbox geometry(Polygon,3035),
    code varchar(7),
    CONSTRAINT city_pkey PRIMARY KEY (id)
)
I will publish it as a layer in geoserver.

**Comment by negroscuro** [comment]
One question, when I check data availability for each city ... should I provide cities with both pluvial floods and heat wave datasets available or having just one of them is ok? do i have to provide two different lists of cities depending if a city has data for pluvial floods and/or for heat waves?
which criteria should I use?

**Comment by fgeyer16** [comment]
> That means, the list of selectable cities in the city selection box depends on the selection the user has made in the countries box (filtered by country code!). @fgeyer16 @patrickkaleta Is that possible?

The first Idea I had was to use the module [Simple Hierarchical Select](https://www.drupal.org/project/shs)(SHS). So We would make the cities child terms of the countries. SHS allows to make tree dependet selections So you would have a Dropdown with countries and would select one. After that selection beside the drop down with the country would appear another one with all cities of this country.An there you would select one. Drawback: In the field only the City would be saved. If we need the country of the study we have to use the cities relationship to the country. For views this should not be a problem because we can filter for the parent term ID instead for the term ID.. But maybe we will end in a death end somewhere else.

Second possibility I know (but have not used yet) is the [dependent field functionality](https://www.drupal.org/docs/8/modules/business-rules/advanced-usage/dependent-field) of Business rules. Here we have two fields one with the city and one with the Country.

**Comment by negroscuro** [comment]
There is a layer published in ATOS Geoserver with all available cities and their Bboxes:
http://services.clarity-h2020.eu:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=2616789.0%2C1411734.375%2C6476075.5%2C4792134.0&width=768&height=672&srs=EPSG%3A3035&format=application%2Fopenlayers3

**Comment by patrickkaleta** [comment]
> Second possibility I know (but have not used yet) is the [dependent field functionality](https://www.drupal.org/docs/8/modules/business-rules/advanced-usage/dependent-field) of Business rules. Here we have two fields one with the city and one with the Country.

I tested this locally and it worked. The relation between the two taxonomies has to be established by an Entity reference in the Cities/Regions taxonomy to the corresponding `Country` taxonomy term.
However, this mentioned [patch](https://www.drupal.org/project/business_rules/issues/2994155) has to be applied to the Business rules module, otherwise it won't work for forms that are being rendered within an ajax modal (which is the case for the context form in a Study).

![city-selection](https://user-images.githubusercontent.com/42167036/58712054-1de4bc80-83c0-11e9-945f-c838cd98b8aa.gif)

**Comment by negroscuro** [comment]
I provided a layer with cities, is there need to know related country as alphanumerical data along with the city data or do we need a new layer with country boundaries?

**Comment by patrickkaleta** [comment]
I created the [Cities/Regions](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview) taxonomy, which is now ready to be filled. This taxonomy currently has (aside the default title and description fields) a field for the Bounding box and a reference to the Countries taxonomy (necessary for limiting the options in the Study-context form). **Country code is not part of this taxonomy, since it is not needed by Drupal for the filtering.** 
@therter if you need the country code for the map compoment (or something else), let me know and I will add that field to the taxonomy.

**Comment by therter** [comment]
@patrickkaleta I don't need an additional field for the country code.

**Comment by therter** [comment]
The city taxonomies are now available in the csis

**Comment by therter** [comment]
I have updated the map-component locally according to the [KISS  approach](https://github.com/clarity-h2020/map-component/issues/24#issuecomment-496434276). 
@patrickkaleta Can you add your changes from your [comment](https://github.com/clarity-h2020/map-component/issues/24#issuecomment-497729679) to the csis site, so that I can complete this issue?

**Comment by patrickkaleta** [comment]
@therter I already created the necessary field in the Study group and configured the forms. Only thing left for me to do is to apply the mentioned patch to the Business rules module, so that this will work also for forms called via AJAX. I will do this today and inform you.

You can already test your map component with this new City/region field, when you edit the study group via this link (shows the edit form without using ajax): https://csis.myclimateservice.eu/group/1/edit

**Comment by p-a-s-c-a-l** [comment]
> Only thing left for me to do is to apply the mentioned patch to the Business rules module, so that this will work also for forms called via AJAX.

I did this already in https://github.com/clarity-h2020/docker-drupal/issues/53#issuecomment-502576926

**Comment by patrickkaleta** [comment]
> > Only thing left for me to do is to apply the mentioned patch to the Business rules module, so that this will work also for forms called via AJAX.
> 
> I did this already in [clarity-h2020/docker-drupal#53 (comment)](https://github.com/clarity-h2020/docker-drupal/issues/53#issuecomment-502576926)

Just realized that we weren't talking about the same patch. For the city selection to work this [patch](https://www.drupal.org/files/issues/2018-08-21/2994155-2.patch) is required.
@p-a-s-c-a-l how did you apply patches so far? @fgeyer16 mentioned [this](https://punkt.de/de/blog/2017/patchen-mit-composer.html) approach to me, which I tested and it worked well in my local environment for the patch I mentioned.

**Comment by p-a-s-c-a-l** [comment]
@therter Status?

**Comment by therter** [comment]
The cities were imported and can be used by the map-component
