### ISSUE TITLE
Can't define *one* study area

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#40]
I am trying to add a new study. At "define area" step, I am stuck with not being able to define just one area bounding box.

![image](https://user-images.githubusercontent.com/2961790/62376703-89bedf00-b541-11e9-86b8-b172bb1c551f.png)

My mouse is released, but the widget still wants me to release it to finish drawing....

By the way the edit button should be probably renamed "toggle edit". Or change when one is in the edit mode...

**Comment by DenoBeno** [comment]
Furthermore, it is very difficult to find the area of interest since the map doesn't zoom out and doesn't provide any search capability either.

By the way, when I managed to get just one BB, this BB wasn't saved.

**Comment by p-a-s-c-a-l** [comment]
> Furthermore, it is very difficult to find the area of interest since the map doesn't zoom out and doesn't provide any search capability either.

That's intentionally. You select the country and city region in the previous step (study context). Then the study area map is locked to this city region. There is no need to zoom out beyond the city region or search, because you are only able to define your study area exactly within this region. We discussed and agreed on this behaviour during the Frankfurt DEV meeting.

> By the way, when I managed to get just one BB, this BB wasn't saved.

Maybe another regression introduced by recent data model changes? @therter, can you please have a look?

**Comment by therter** [comment]
There was no city selected. 
Now the component shows a hint that the user should select a city, if no city is selected and the component does not switch to the edit mode without a city.
