### ISSUE TITLE
Set initial Bounding Box Broken

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#53]
Two main Problems:

1) what we get from drupal:
minx=1.9429e+06&miny=4.64769e+06&maxx=2.01214e+06&maxy=4.72026e+06
results in: Error: "Invalid LatLng object: (1.9429e 06, 4.64769e 06)"

2) if we remove the exponent, the bbox is the middle of the Atlantic ocean instead of naples: [Map](https://csis.myclimateservice.eu/apps/map-component/build/DataPackagePreviewMap/?host=https://csis.myclimateservice.eu&datapackage_uuid=a8ff7930-4a9f-4289-8246-3383ba13c30f&write_permissions=1&minx=1.9429&miny=4.64769&maxx=2.01214&maxy=4.72026)!

This is the bbox in Drupal: 

![grafik](https://user-images.githubusercontent.com/1788226/64183537-53d78800-ce6a-11e9-944b-8604bf9dad87.png)

And this is how it is set in leaflet:

```js
    this.initialBounds[0][0] = this.queryParams.minx;
    this.initialBounds[0][1] = this.queryParams.miny;
    this.initialBounds[1][0] = this.queryParams.maxx;
    this.initialBounds[1][1] = this.queryParams.maxy;

<Map
          id="#map"
          className="simpleMap"
          scrollWheelZoom={true}
          bounds={this.initialBounds}
          loadingControl={false}
          onViewportChanged={this.onViewportChanged.bind(this)}
```

Example bbox retrieved from drupal: [1.9429, 4.64769] [2.01214, 4.72026]

**Comment by therter** [comment]
The coordinates are in EPSG:3035, but we need the EPSG:4326 coordinates. If you look [here](https://csis.myclimateservice.eu/node/918/edit), then you see the coordinates in EPSG:4326 and in EPSG:3035. The View of the dp_spatial_extent taxonomy is very confusing, because the title of the map is "Bounding box (EPSG:4326)" and the coordinates under the map are in EPSG:3035.

Either we try to get the EPSG:4326 coodinates from drupal (drupal has the coordinates in EPSG:4326) or we transform the coordinates in the map-component with proj4 like

```
const targetProj = "+title=WGS 84 (long/lat) +proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees"
const sourceProj = 'PROJCS["ETRS89 / LAEA Europe",  GEOGCS["ETRS89", DATUM["European_Terrestrial_Reference_System_1989", SPHEROID["GRS 1980",6378137,298.257222101, AUTHORITY["EPSG","7019"]], TOWGS84[0,0,0,0,0,0,0], AUTHORITY["EPSG","6258"]], PRIMEM["Greenwich",0, AUTHORITY["EPSG","8901"]], UNIT["degree",0.0174532925199433, AUTHORITY["EPSG","9122"]], AUTHORITY["EPSG","4258"]], PROJECTION["Lambert_Azimuthal_Equal_Area"], PARAMETER["latitude_of_center",52], PARAMETER["longitude_of_center",10], PARAMETER["false_easting",4321000], PARAMETER["false_northing",3210000], UNIT["metre",1, AUTHORITY["EPSG","9001"]], AUTHORITY["EPSG","3035"]]';
const cornerMin = proj4(sourceProj, targetProj, [4647690,1942900]);
const cornerMax = proj4(sourceProj, targetProj, [4720260, 2012140]);

 this.initialBounds[0][0] = cornerMin[0];
    .
    .
    .
```

**Comment by p-a-s-c-a-l** [comment]
@maesbri @denobeno

Can you please explain How to obtain the spatial extent in 4326? i thought this epsg discssion was Finally settled and **inside** drupal we use 4326 only which is **perfectly fine** and Now implemented in the map component.  We use 4326 in study area and   Cities taxonomy so why Not in spatial extent?

**Comment by DenoBeno** [comment]
I'm not 100% sure, but you might be looking at the wrong data. Or that the
data itself is wrong.

Last time I looked into this, I realised the following.

First, the two sets of the coordinates we are talking about are very
different in nature.

- the one that's useful natively by drupal and Google and... is the one we
learn in school, with coordinates like 45N, 16E.
- the one that's used by our maps has coordinates in tens of thousands.

Now, if one looks at dp_spatial, this one also has two sets of coordinates:
the ones written in four variables named x_min, y_min, x_max and y_max and
the ones stored as a polygon in a single geospatial variable.

The first set of the four variables is of no use within Drupal. The second
set can be visualised on a map, but when I tried to do this, it turned out
that the coordinates were wrong. At first I thought that the coordinates
are in wrong encoding, but that's impossible since drupal geo-variables
check input and rejected anything that's out of -90/90:-180/180 range.

So I concluded that the spatial coordinates were simply wrong, most
probably the lon/lat order was reversed.

I think to remember Patrick saying that this is indeed so and that he plans
on uploading new values, but I haven't looked into this later on.

Hope this helps.

**Comment by DenoBeno** [comment]
What I'm talking about is the data that's in the cities taxonomy.

As for the data that's in the dp_spatial, here the situation is a bit
different:
- The four xmin etc variables may be empty or contain any garbage. We
aren't using them, they just haven't been deleted to avoid problems with
the DB.
- the bounding box geospatial variable contains correct data in the sense
that it's visualised on a map and shows up correctly.

The reason why I'm mentioning the cities taxonomy is that I wanted to have
all of the cities also available in the dp_spatial but it turned out that
the data was wrong.

**Comment by p-a-s-c-a-l** [comment]
OK. Thanks. That means that minx; miny; maxx; maxy; should be deleted from spatial extent or at least renamed. Right @patrickkaleta @maesbri  ?

**Comment by patrickkaleta** [comment]
>So I concluded that the spatial coordinates were simply wrong, most
probably the lon/lat order was reversed.
>I think to remember Patrick saying that this is indeed so and that he plans
on uploading new values, but I haven't looked into this later on.

No sorry @DenoBeno that was not me, but I also remember that this was discovered/discussed in a telco, probably by @therter and/or @negroscuro if I'm not mistaken.


>OK. Thanks. That means that minx; miny; maxx; maxy; should be deleted from spatial extent or at least renamed. Right @patrickkaleta @maesbri ?

I'll prepend a "`remove_`" to the 4 fields in question in the [spatial extent](https://csis.myclimateservice.eu/admin/structure/types/manage/spatialextent/fields) (just like we did it in other cases).

**Comment by p-a-s-c-a-l** [comment]
workaround implemented.
