### ISSUE TITLE
No "EMIKAT" layers shown on the maps

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#80]
Today, no EMIKAT-produced layers show up on the map. I tried with old study and with a completely new one: tables are OK, maps are empty. No local hazard (temperatures), no population, no mortality.

**Comment by p-a-s-c-a-l** [comment]
[EMIKAT WMS](https://service.emikat.at/geoserver/clarity/) is not responding. We'll set-up [service monitoring](https://github.com/clarity-h2020/csis-technical-validation/issues/2) for this kind of issues.

**Comment by humerh** [comment]
The URL-Template is like this:
url template https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2974&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT='${study_variant}' and TIME_PERIOD='${time_period}' AND EMISSIONS_SCENARIO='${emissions_scenario}' AND EVENT_FREQUENCY='${event_frequency}' AND **SZ_ID=${emikat_id}**&styles=T_UTCI
 with 5 variables

but the emikat_id was not expanded:

https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2974&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Occasional%27%20AND%20SZ_ID=&styles=T_UTCI

This error has to be corrected by the CSIS-Team

**Comment by humerh** [comment]
Zusätzlicher Grund für das Fehlen eines Ergebnisses:
Die Stadt heisst bei "Martality rates":
![image](https://user-images.githubusercontent.com/20284964/73354444-05ea7300-4296-11ea-9db1-26f0de5abcfc.png)

In der Definition der Study aber LIEPAJA.
Damit werden keine Impacts gerechnet.

**Comment by p-a-s-c-a-l** [comment]
Works [again](https://csis.myclimateservice.eu/study/33/step/1513/view/maps).

**Comment by DenoBeno** [comment]
Same problem again today. Asked Heinrich to see if it's on the EMIKAT side...

We badly need a monitoring service to detect this type of issues.

**Comment by p-a-s-c-a-l** [comment]
Apparently a server server issue. Works again: 

![grafik](https://user-images.githubusercontent.com/1788226/74005147-40c86700-4978-11ea-8a20-c18194f58dd8.png)

[Monitoring](https://github.com/clarity-h2020/csis-technical-validation/issues/2) is on the todo list.

**Comment by DenoBeno** [comment]
Yes, @humerh  told me that the server has experienced memory overload. 

Apparently something tried to get a full europe view of some data from it at some point. Don't know the details, @humerh could you please elaborate what happened?

This issue has a simple workaround (restart server), but we can't call Heinrich every time it happens. I suppose we need a separate issue for this bug, not sure if one already exists...

**Comment by p-a-s-c-a-l** [comment]
urgent @humerh @negroscuro 

Mattia needs to perform a series of example studies in various Italian cities for the state level agency,  so that he can to show that we can do studies in several Italian cities (regardless of the quality of numeric output).

Now, it seems that no [HC-LE](https://csis.myclimateservice.eu/study/90/step/2999/view/maps) or [impact](https://csis.myclimateservice.eu/study/90/step/3002/view/maps) is calculated for [this study](https://csis.myclimateservice.eu/study/90).

EMIKAT GeoServer returns [an empty image](https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720410101-20701231%27%20AND%20EMISSIONS_SCENARIO=%27rcp85%27%20AND%20EVENT_FREQUENCY=%27Occasional%27%20AND%20SZ_ID=3337&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_A%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&maxZoom=undefined&minZoom=undefined&tileSize=1536&attribution=&bbox=1271912.150665333,5530371.870489074,1279250.1053807097,5537709.825204453).

Is this related to the discussion about the [re-calculation of all HC-LEL input layers](https://github.com/clarity-h2020/data-package/issues/59#issuecomment-583712125)? Are the "old" HC-LE input layers still available so that we can create studies even if the results are not accurate yet?

What about the [Export Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/23), does it have any influence on EMIKAT calculations, @humerh ?

**Comment by DenoBeno** [comment]
If it's urgent, @negroscuro needs to know about it to generate these first. The calculation is changing now and I doubt that we can have both the "old" and the "new" variant working at the same time.

**Comment by negroscuro** [comment]
Which cities are the ones needed for this Plinivs event?

**Comment by p-a-s-c-a-l** [comment]
Clearly and [EMIKAT Issue](https://github.com/clarity-h2020/emikat/issues/33)
