### ISSUE TITLE
Please change the way "default" layers are shown on the map

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#84]
While testing for https://github.com/clarity-h2020/data-package/issues/59, I realised that following things need to be changed for the "default" layers presentation:

- [ ] **Remove the "built up areas"**. This information is now spread over 3+2 "building" layers, the build up areas layer doesn't/will not exist anymore.
- [ ] **Add the "sport facilities" layer**. It's missing from the map now. (ask @negroscuro for details)
- [ ] Make it **possible to choose zero to n "default" layers**, like we do for the background layers now. These layers don't overlap, this makes them perfect for multi-layer screenshots.
- [ ] Maybe also **rename this layers group**? (e.g. "CLARITY backgrounds"?) 

Last point is mostly cosmetics, but there is a bit of overlap between "background" and "default" layers. Maybe we should merge the two groups and drop the overlapping layers? 

Or call this "CLARITY background" as opposed to background layers from other sources? That would IMO be a good think, e.g. to be able to demonstrate the difference between the urban atlas "buildings" layers and ours.

**Comment by negroscuro** [comment]
Sports layer is currently added.
I also removed built up as you asked.

**Comment by p-a-s-c-a-l** [comment]
> * **Remove the "built up areas"**. This information is now spread over 3+2 "building" layers, the build up areas layer doesn't/will not exist anymore.
> * **Add the "sport facilities" layer**. It's missing from the map now. (ask @negroscuro for details)

O.K. This is a modification of the respective resources the European Data Package. I can look into this. 

> Make it possible to choose zero to n "default" layers, like we do for the background layers now. These layers don't overlap, this makes them perfect for multi-layer screenshots.

Considering how resources and references are modelled in CSIS Drupal, this is currently not possible without changing the data model. We could add a boolean field 'selected' to the resource entity type, however, since a resource can contain [multiple references](https://github.com/clarity-h2020/map-component/issues/72) (service paths) each of which is expanded into a separate layer, all layers of the resources would be selected. This is e.g. the case for the [EEA Discovery Map Services Resource](https://csis.myclimateservice.eu/node/2077), which consists of 8 different references and layers respectively. Furthermore, since resources can be arbitrarily combined in data packages, it would be counter productive to define the default selection status at the level of the resource. It would have to be defined at the level of the data package making the data package data model ire complex (keeping information on the state of resources). 

> Maybe we should merge the two groups and drop the overlapping layers?
No those are conceptually different things. The name 'default' is just a fallback name if no hazard type is associated with the resource, e.g. for exposure resources.

**Comment by p-a-s-c-a-l** [comment]
> Make it possible to choose zero to n "default" layers, like we do for the background layers now. These layers don't overlap, this makes them perfect for multi-layer screenshots.

O.K. Now I understand what you mean by 'default' layers. Ypu are talking about the are the Hazard LE Input Layers in the HC-LE step. The layer group name 'default' is misleading but as before, it is just a fallback name. What we can do without changing data models, etc. is use the name of the GL step as group title in this case 'Hazard Characterization - Local Effects'. 

ATM it's not easily possible to chose more than one because of [this request](https://github.com/clarity-h2020/csis/issues/104#issuecomment-577741543).

**Comment by p-a-s-c-a-l** [comment]
> we could introduce a new *'category'* tag at the level of the resource, so that layers are sorted into in respective category-folders of the Map Component's layer widget.

See https://github.com/clarity-h2020/data-package/issues/21#issuecomment-589573088

**Comment by claudiahahn** [comment]
> ATM it's not easily possible to chose more than one because of this request.

Sorry for any confusion. My request was mainly to be able to unselect layers. I agree that it would be nice to be able to select more than 1 background layer for display. This might also become important for the basic screening method.

**Comment by p-a-s-c-a-l** [comment]
> select more than 1 background layer for display

This is currently possible. **[Background Layers](https://csis.myclimateservice.eu/taxonomy/term/5238)** have check boxes (0-n selectable) **any another layers** have de-selectable option boxes (0-1 selectable). The reason is simple: *Most* background layers are based on vector data and are partially transparent, so it makes sense to show several of them in one map (buildings + roads + vegetation, ...). Any other layers are *in most cases* gridded raster layers, so showing more than one at a time does not offer any benefit because they obscure each other.

Of course, we've got also some non-transparent background layers and a few transparent 'other' layers (the 'default' Urban-Atlas based HC-LE input layers for example). So the current solution is not optimal, but IMHO a compromise we can live with. 

While we could implement an **exception** for the HC-LE input layers and allow multi-selection via checkboxes, we have to be aware that HC-LE includes also non-transparent raster layers (TMRT, etc.) calculated by EMIKAT. 

There was also an idea to [allow user to overlay several layers and decide how to colour-code each](https://github.com/clarity-h2020/map-component/issues/59#issuecomment-541740973), but this is technically difficult to implement [on client side](https://github.com/clarity-h2020/csis/issues/105#issuecomment-538870529) and the [current situation](https://github.com/clarity-h2020/csis/issues/145) does not allow us to invest effort on costly features.

**Comment by DenoBeno** [comment]
"clarity background" sounds good to me. The reason why I asked for a
possibility to choose multiple was because these layers never overlap.

**Comment by p-a-s-c-a-l** [comment]
I've introduced a new tag *[clarity-background-layer](https://csis.myclimateservice.eu/taxonomy/term/5702)* and tagged the HC-LE input layers accordingly.

![grafik](https://user-images.githubusercontent.com/1788226/75560523-99ee5c80-5a45-11ea-918e-e24a39e80314.png)

[Map Component](https://csis.myclimateservice.eu/apps/map-component/build/DataPackagePreviewMap/?host=https://csis.myclimateservice.eu&study_area=POLYGON%20((55%2072,%2055%2030,%20-30%2030,%20-30%2072,%2055%2072))&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&write_permissions=1&grouping_tag=taxonomy_term--eu_gl) on csis.myclimateservice.eu (which is [still](https://github.com/clarity-h2020/csis/issues/145) the **old** DEV server) is updated.

@negroscuro Can you please create an new resource for the sports layer in the [European Wide Data Package](https://csis.myclimateservice.eu/node/682/edit). Please tag it with *clarity-background-layer*, **not** with *background-layer* and *[local-effects](https://csis.myclimateservice.eu/taxonomy/eu-gl/hazard-characterization/local-effects)*. Thanks!

**Comment by negroscuro** [comment]
I just updated CKAN with new sports data:
https://ckan.myclimateservice.eu/dataset/sports

Then I modified built_up obsolete entry in CSIS under European wide data package (https://csis.myclimateservice.eu/node/682), sports layer is:
https://csis.myclimateservice.eu/node/3637

**Comment by ghilbrae** [comment]
@negroscuro can you please update the two resources in CKAN with proper URLs or files to the actual data? This way they lead to nowhere. Thanks!!

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by negroscuro** [comment]
@ghilbrae sorry I missplaced URL, now it is corrected.

**Comment by ghilbrae** [comment]
@negroscuro  Thanks!!
