### ISSUE TITLE
extracting data from climate index maps

### ISSUE THREAD

**Issue by claudiahahn** [clarity-h2020/map-component#98]
@ghilbrae, @LauraMTG, @luis-meteogrid  
Is there a way to extract data from the maps for the study area selected? 
I have the impression that was done initially as we tried to display the hazard table. Or am I mistaken? It would be great to somehow be able to get the value of the indices for the historical and future time periods, either displayed when moving over the map or extracted and made available in table format.  

@p-a-s-c-a-l: Not sure if it is the right place to post this.

**Comment by p-a-s-c-a-l** [comment]
As an example, for the [PI_rr20mm_historical_19710101-20001231_ensmean](https://geoserver.myclimateservice.eu/geoserver/europe/wms?service=WMS&version=1.1.0&request=GetMap&layers=europe%3API_rr20mm_historical_19710101-20001231_ensmean&bbox=2145642.726143716%2C982955.8095900388%2C6605432.868301096%2C5706496.981659953&width=725&height=768&srs=EPSG%3A3035&format=application/openlayers) layer we can make a [GetFeatureInfo](https://geoserver.myclimateservice.eu/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&FORMAT=application/json&TRANSPARENT=true&QUERY_LAYERS=europe:PI_rr20mm_historical_19710101-20001231_ensmean&LAYERS=europe:PI_rr20mm_historical_19710101-20001231_ensmean&FEATURE_COUNT=1&X=50&Y=50&SRS=EPSG%3A3035&STYLES=&WIDTH=600&HEIGHT=400&BBOX=4300114.2789779045%2C2340630.3859436535%2C5287185.965743287%2C3327702.0727090365&INFO_FORMAT=application/json&EXCEPTIONS=application/json) (user clicks on the map) and we'll get the following response from the server:

```json
{
    "type": "FeatureCollection",
    "features": [{
            "type": "Feature",
            "id": "",
            "geometry": null,
            "properties": {
                "GRAY_INDEX": 2.066666603088379
            }
        }
    ],
    "totalFeatures": "unknown",
    "numberReturned": 1,
    "timeStamp": "2020-06-25T12:15:00.201Z",
    "crs": null
}
```

The ominous `GRAY_INDEX` is the value we are looking for. Unfortunately, there is no information on the *variable name* or the *unit*. At least, this information is available in [the legend](https://geoserver.myclimateservice.eu/geoserver/europe/wms?service=WMS&request=GetLegendGraphic&version=1.1.0&format=image%2Fpng&width=20&height=20&layer=europe:PI_rr20mm_historical_19710101-20001231_ensmean&style=&legend_options=forceTitles:on). So what we can do here is showing this plain value, but not much more.

**Comment by claudiahahn** [comment]
That would already be very helpful! as long as only the number is displayed and not the whole response from the server that you have copied in earlier. :)

**Comment by p-a-s-c-a-l** [comment]
> Uncaught TypeError: xml_js__WEBPACK_IMPORTED_MODULE_4__.parseString is not a function

**Comment by p-a-s-c-a-l** [comment]
@claudiahahn @RobAndGo 

Good News: I've implemented a pop-up to query information from layers and show the values.

Bad News: It's not possible to reliably determine the last selected layer if multiple layers are selected:

![map](https://user-images.githubusercontent.com/1788226/86230244-1ed2b980-bb91-11ea-9b9b-925002a85442.gif)

This is due to issues with [React Virtual DOM](https://reactjs.org/docs/faq-internals.html) and we have no control over that. This means, if multiple layers are enabled, it cannot be reliably predicted for which layer the information is shown. Since I've spent already too much time trying to work around this issue, I'm not going to fix it. 

The new functionality is currently enabled on CSIS DEV only. You can test it [here](https://csis-dev.myclimateservice.eu/study/25/step/3681/view/maps).

**Comment by RobAndGo** [comment]
This is a great feature! Thanks @p-a-s-c-a-l!! 

Perhaps one solution would be to add a warning text at the base of the map page stating something like "Note: In order to avoid any ambiguity, mouseover values are valid only when **one layer** is selected."

It would be a bonus if you could cut the values down to one decimal value, either by rounding, or simply by removing everything after the first digit after the decimal.

**Comment by claudiahahn** [comment]
yes, that is great! Thank you @p-a-s-c-a-l !
And it even displays the layer name, so the user at least knows what he is looking at. 
@RobAndGo ideas regarding a short text below the maps and cutting the values to one decimal value are good
